export type CartItemType = "product" | "combo" | "gift" | "request";
export type CartLine = {
  productId: string;
  productDetails?: Record<string, unknown>;
  quantity: number;
  itemType?: CartItemType;
  selectedProductIds?: string[];
};
export type UserDetails = {
  _id?: string;
  id?: string;
  customId?: string;
  sessionExpiredTime?: string;
  username?: string;
  mobileNumber?: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  mobile?: string;
  email?: string;
  roleName?: string;
  role?: string;
  permitNumber?: string;
  dateOfBirth?: string;
  age?: number;
  address?: string;
  pincode?: string;
  googleMapsLocation?: string;
  digilockerStatus?: string;
  digilockerVerifiedAt?: string | null;
  digilockerVerificationDate?: string | null;
  profileImageUrl?: string | null;
  permitDocumentUrl?: string | null;
  profileFileId?: string | null;
  permitDocumentFileId?: string | null;
  userType?: string;
  active?: boolean;
  deletedAt?: string | null;
  isPinSet?: boolean;
  hasPin?: boolean;
  loginRequestId?: string;
  createdAt?: string;
  updatedAt?: string;
  __v?: number;

  verified?: boolean;
  cameFromLoginHere?: boolean;
  aadhaarNumber?: string;
  aadhaarVerified?: boolean;
  digilockerOtpVerified?: boolean;
  verificationComplete?: boolean;
  ageVerified?: boolean;
  profileComplete?: boolean;
  formDrafts?: {
    login?: { name: string; mobile: string };
    loginHere?: { phoneValue: string; countryCode: string; dialCode: string; password: string };
    otp?: string;
    digilockerOtp?: string;
    aadhaar?: string;
    ageVerification?: { confirmed: boolean };
  };
  [key: string]: unknown;
};
